
spring:
  application:
    name: wonderworld
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:4000/wonderworld
    driver-class-name: com.mysql.cj.jdbc.Driver

kafka:
  server: localhost:29092
  topics:
    regist: regist.topic

