
spring:
  application:
    name: wonderworld
  datasource:
    username: root
    password: password
    url: jdbc:mysql://db:3306/wonderworld
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /wonderworld

kafka:
  server: kafka:9092
  topics:
    regist: regist.topic
