apiVersion: apps/v1
kind: Deployment
metadata:
  name: wonderworld-deployment
  namespace: wonderworld-dev
  labels:
    app: wonderworld-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wonderworld-deployment
  template:
    metadata:
      labels:
        app: wonderworld-deployment
    spec:
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - localhost
      containers:
        - name: wonderworld-deployment
          image: wonderworld:1.3
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /wonderworld/actuator/health
              port: http
            failureThreshold: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /wonderworld/actuator/health
              port: http
            failureThreshold: 3
            periodSeconds: 30
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx1024m"
            - name: SPRING_CONFIG
              value: "/home/app/config/application.yaml"
            - name: TIME_ZONE
              value: "-Dlogback.timezone=Asia/Bangkok"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wonderworld-secret
                  key: spring.datasource.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wonderworld-secret
                  key: spring.datasource.password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: wonderworld-secret
                  key: spring.datasource.url
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: wonderworld-volume
              mountPath: /home/app/config/application.yaml
              subPath: application.yaml
      volumes:
        - name: wonderworld-volume
          configMap:
            name: wonderworld-configmap
