apiVersion: v1
kind: Service
metadata:
  name: wonderworld-service
  namespace: wonderworld-dev
  labels:
    app: wonderworld-label
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  selector:
    app: wonderworld-deployment